### PR TITLE
remove editor recovery file

### PR DESCRIPTION
**Pull request by mickeyn**

### CODE REVIEW

**Comment by oalders** [comment]
Broken build is unrelated

**Comment by mickeyn** [comment]
@oalders yeah, that diff test is failing for other PRs... didn't investigate, but it's unrelated

**Comment by oalders** [comment]
I've got a branch that I'm working on to fix that failure, but it's not ready yet.  However, the merge button is currently unavailable.  ;)

**Comment by oalders** [comment]
I'll get back to that branch tomorrow and we'll see about unblocking the builds.  I think this one isn't urgent?

**Comment by mickeyn** [comment]
not at all :)

**Pull request merged**
