### PR TITLE
use new Search::Elasticsearch and ElasticSearchX::Model

### PR DESCRIPTION
**Pull request by haarg**
This seems to be working OK, but could use some additional testing, especially in the scripts.

### CODE REVIEW

**Comment by oalders** [comment]
Does this PR need more tests or should we merge?

**Comment by haarg** [comment]
I'd appreciate it if people could do some manual testing of the scripts.

**Comment by mickeyn** [comment]
@haarg I'll try to do some live testing tonight

**Comment by mickeyn** [comment]
tested a few scripts manually, seems to be working fine, merging

**Comment by haarg** [comment]
Had to revert this.  The script code isn't using values from the config file to connect to ES, and isn't loading the config files correctly.

**Pull request merged**
