### PR TITLE
[WIP] Adds permissions type for 06perms

### PR DESCRIPTION
**Pull request by oalders**

### CODE REVIEW

**Comment by oalders** [comment]
@andreeap have you had a chance to test this yet?

**Comment by andreeap** [comment]
I forgot to update what I found out here, sorry. When I ran the script I got this:
<pre><code>vagrant@metacpan-dev:~/metacpan-api$ ./bin/run bin/metacpan permission
Can't call method "set_class" on an undefined value at /home/vagrant/carton/metacpan-api/lib/perl5/ElasticSearchX/Model/Index.pm line 82.</code></pre>

**Comment by oalders** [comment]
Now that PAUSE has removed module permissions, this pull request will need to be updated to reflect that.

**Comment by oalders** [comment]
Closing in favour of #624

**Pull request closed without merging**
