### PR TITLE
Removed needless calls to model settings (raw)

### PR DESCRIPTION
**Pull request by mickeyn**
Removed calls to 'raw' (ESX::Model) for the new API endpoints
which don't use the model for querying.

Changed all 'inflate(0)' calls to 'raw' (does the same) for
consistency.

Moved 'raw' calls from controllers back to the document where
possible (some cases will be dealt with later).

### CODE REVIEW

**Comment by oalders** [comment]
This has some merge conflicts

**Comment by oalders** [comment]
Now it has more merge conflicts. :(

**Comment by mickeyn** [comment]
fixed conflicts

**Comment by mickeyn** [comment]
@oalders poke :) (I have another change waiting for this one to be merged)

**Pull request merged**
